### ISSUE TITLE
Link to repo on Mozilla or Blogspot?

### ISSUE THREAD

**Issue by kevinmickey** [stephanmahieu/formhistorycontrol-2#1]
Can you link to this repo on the Mozilla Add-ons page, or on your Blogspot blog (or ideally both)?  Thanks!

**Comment by stephanmahieu** [comment]
I am planning to move some or maybe all info from the blog to the github wiki/pages and link to these from the add-on, and add-ons page..

**Comment by jidanni** [comment]
Yes it takes detective work to find this GitHub project.

**Comment by stephanmahieu** [comment]
Mozilla homepage now set to github pages: https://stephanmahieu.github.io/fhc-home/
Github pages links to github (see footer)
