### ISSUE TITLE
Bring back the "Manage entries for this field" menu item

### ISSUE THREAD

**Issue by obones** [stephanmahieu/formhistorycontrol-2#102]
I've been using Form History Control inside the SeaMonkey suite from Mozilla for a long time and when I right click on a form field, there is an entry that reads "Manage entries for this field".
This allows to display the list of saved values only for the given field, thus allowing to easily remove some just for this field. I use most often for a date entry that only allows future dates but remembers everything so that I can remove dates from the past. This allows me to limit the suggestion list to a small set and not have it cluttered by values that are no longer valid.

Because the SeaMonkey suite is no longer maintained, it is time for me to move on to Firefox.
I was able to install Form History Control inside it, but there is no "Manage entries for this field" menu item, only the "Manage history" item. And because I have no idea how the field is named, I can't find the elements I am looking for.

I looked around and saw no equivalent to the "Manage entries for this field" option. Have I missed something?

If not, could this be considered for a future release? It would allow me to get back the level of control I was used to having inside SeaMonkey.

Thanks a lot for your help and efforts

**Comment by stephanmahieu** [comment]
I think I can implement the "Manage entries for this field" relatively easy by adding the menu entry which would open the main dialog and additionally putting the name of the field in the Searchbox.


> And because I have no idea how the field is named, I can't find the elements I am looking for.

There still is an option in the context menu to "Show fields on the current page" which reveals the names of all fields found on the page.

**Comment by stephanmahieu** [comment]
Introduced in release 2.5.7.0 October 8, 2023.
The right-click context menu, when opened from within an input field will offer a list with only items for that field.

The option to only show all fields for the current page is very tricky. Single line text fields are still stored without the URL they originated from, so they can not be identified (the old version used the history db for that). Until the URL is stored for every field (feature request #101), I can not implement a "Show fields on the current page".
