### ISSUE TITLE
Ability to limit saved instances for specific field

### ISSUE THREAD

**Issue by TonyGravagno** [stephanmahieu/formhistorycontrol-2#105]
We can spend a lot of time to properly craft the text in a text area. Examples include a GitHub issue like this one, a forum posting, browser-based email body text, etc. The longer we spend there, the more vulnerable we are to losing the carefully modified details. So I set FHC to save at 5 second intervals, minimum 1 minute, and when content changes by 10 characters.

The problem that results is evident throughout the FAQs and issue reports here. There is too much data that is saved and this results in the tools falling over under the load.

Maybe I missed it but I think a solution to this would be if we could specify a limit on the amount of data saved per-field. I don't need a thousand backups of the field I'm typing. Given the pattern above, I'd be happy with the last 1 minute, or 12 saves. As a bonus I'd appreciate saving one snapshot per minute that I'm active in a form. Then in case I delete something and want to go back to it, it might still be in there.

Similarly, after posting form, I don't think there is a need to continue saving the detailed history that led up to the final submission. I would be happy with the last update plus the last 2 snapshots. This would eliminate the huge amount of history for a single field in a single form, and eliminate a lot of grief associated with a huge FHC database.

Thanks for consideration

As an aside, I recently started using FHC. I've been looking for a solution to this problem for years. I've tried others that were inadequate. I really appreciate the effort in this plugin and the quality and scope of features. Thank you VERY much @stephanmahieu !

**Comment by stephanmahieu** [comment]
I would suggest not saving that many versions if you do not really need them. Increasing the update interval will already protect you from losing too much data, especially if you are very fast at typing.

Maybe you do not fully understand how formhistory saves formhistory. By setting the update interval to 5 seconds, every change you make in an edit field will be stored in a single entry by FHC every 5 seconds. So you can type for many many minutes and every change will be stored in that same entry in FHC. Only if the criteria are met for starting a new version, a new entry will be added to capture subsequent changes you make to that same edit field.
So starting a new version every minute is not really necessary, only use this feature if you are interested in the individual changes you make over time.

_In fact, everything you type is being queued and saved at set intervals, so only if FF crashes will you lose the last seconds of typing._
