### ISSUE TITLE
FHC Export of old form contents fails

### ISSUE THREAD

**Issue by grafenhofer** [stephanmahieu/formhistorycontrol-2#106]
**Describe the bug**
Running fhcExport I receive an empty formhistory.xml.

**To Reproduce**

I run

`java -jar fhcExport-1.0.0.jar -p ~/.mozilla/firefox/YYY.default-release/`

and receive

**the output**

Start formhistory export
- profile directory: /home/XXX.mozilla/firefox/YYY.default-release/
- destination file : formhistory.xml

```
checking outputfile:        OK
checking profile directory: OK
reading inputfields:       Retrieve input fields failed. [SQLITE_CORRUPT]  The database disk image is malformed (malformed database schema (moz_history_to_sources) - near "WITHOUT": syntax error)
 0
reading multilinefields:    skipped, non existing or empty db (cleanup.sqlite)
writing data:               OK
```

**Expected behavior**
formhistory.xml should contain all old form data

**Desktop:**
 - OS: Fedora release 32 (Thirty Two)
 - Browser Firefox 81.0.1 (64-bit)
 - openjdk version "1.8.0_265", OpenJDK Runtime Environment (build 1.8.0_265-b01), OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)

**Comment by stephanmahieu** [comment]
It looks like you are trying to use fhcExport on a profile directory belonging to a modern version of Firefox. The standalone export utility is designed to export formhistory data from Firefox versions prior to the  WebExtension versions. So only version up to 51 are supported.

If you wish to export the formhistory from newer version, you can do so from FormHistoryControl itself. See the [help](https://stephanmahieu.github.io/fhc-home/Manual/manual/#import-export) fo more information on exporting/importing.
