### ISSUE TITLE
FF - instant crash

### ISSUE THREAD

**Issue by Intenditore** [stephanmahieu/formhistorycontrol-2#107]
Win 8.1, FF 81.0.2 
I experienced major slowdowns and than random crashes sometimes right after the start, more and more often until I couldn't start FF at all. 
Turning off all extentions and than re-enabling them one by one I found the reason is Form History Control :(
Fix it please :eyes:

**Comment by stephanmahieu** [comment]
I do not believe the plugint itself is causing the crash, probably your local Storage (IndexedDB) or some file is corrupted. See [Known Issues](https://stephanmahieu.github.io/fhc-home/Manual/KnownIssues/#known-issues) for some more information.

Try creating a new profile or remove FHC and re-install.

**Comment by shocked-gamer** [comment]
also update to the latest v82.0 in case the crashes are caused by the old version.

**Comment by stephanmahieu** [comment]
@Intenditore If FHC is the only enabled extension you still get crashes?

**Comment by stephanmahieu** [comment]
Got no response from @Intenditore and received no similar reports or issues.
Closing this issue.
