### ISSUE TITLE
Write Version 2 introduction

### ISSUE THREAD

**Issue by jidanni** [stephanmahieu/formhistorycontrol-2#11]
We [read](https://formhistory.blogspot.tw/2009/06/introduction-to-form-history-control.html),
> Following instructions are for the old (1.4.0.6) version!
> A new version covering version 2.* will be published shortly...

Please remember to write the Version 2 introduction, and then close this issue.

**Comment by stephanmahieu** [comment]
The manual is now on github pages: https://stephanmahieu.github.io/fhc-home/

**Comment by stephanmahieu** [comment]
Fixed
