### ISSUE TITLE
Explain the permission for downloads (ToDo: Explain all permissions)

### ISSUE THREAD

**Issue by davidmef** [stephanmahieu/formhistorycontrol-2#111]
**Is your feature request related to a problem? Please describe.**
Version 2.5.31 requests a permission to download and modify the download history. I cannot find an explanation.

**Describe the solution you'd like**
Explain the reason for the new permission.
Explain the reason for the earlier permissions as well.

**Describe alternatives you've considered**
Remaining on an old version.

**Comment by birdie-github** [comment]
Have you read the release notes?

> 2.5.3.0 October 25, 2020
> Export now uses the downloads API (downloads permission added)

**Comment by stephanmahieu** [comment]
Download permission is needed for manually exporting your formhistory as a file, see the [manual](https://stephanmahieu.github.io/fhc-home/Manual/manual/#export) for a detailed explanation.

Like the release-notes state, the add-on now uses the downloads-API which requires the _download_ permission.

**Comment by stephanmahieu** [comment]
On my ToDo list: List the permissions this add-on requires with a short explanation.

**Comment by stephanmahieu** [comment]
Permissions is now explained in the online manual, see: [which-permissions-does-form-history-control-require](https://stephanmahieu.github.io/fhc-home/Manual/Permissions/#which-permissions-does-form-history-control-require)

**Comment by youk** [comment]
> 
> 
> Download permission is needed for manually exporting your formhistory as a file, see the [manual](https://stephanmahieu.github.io/fhc-home/Manual/manual/#export) for a detailed explanation.
> 
> Like the release-notes state, the add-on now uses the downloads-API which requires the _download_ permission.

Please make that permission optional. Starting with Firefox 84 there will be out-of-the-box UI for managing optional permissions.

**Comment by stephanmahieu** [comment]
Already done and commited 2 days ago, it will be in the next release.

**Comment by youk** [comment]
Thank you.
