### ISSUE TITLE
Translation need update for release 2.5.5.0 (Greek, Russian, Korean)

### ISSUE THREAD

**Issue by stephanmahieu** [stephanmahieu/formhistorycontrol-2#113]
I am in the process of releasing update 2.5.5.0.

I have added 2 strings in the messages.json file (prefixed with XXX so you can easily find them and with the text still untranslated).
XXXexportErrorTitle
XXXexportErrorNoPermission
_Korean is still missing 13 translated strings_

Could you please provide an update?
TIA

PS
_With this new release the messages.json provided with the add-on will no longer be converted to ascii making it perhaps easier to translate in the future._

Pinging past translaters: @shocked-gamer, @VADemon and @limerainne 

- [x] Greek
- [x] Russian
- [ ] Korean

**Comment by shocked-gamer** [comment]
the "downloads permission" is the same for downloading/pausing/canceling/resuming files in the FF download manager panel?

**Comment by stephanmahieu** [comment]
The downloads permission is only applicable to the add-on. It allows downloading files to your local computer using the save-as dialog. If you download a file with the add-on it will indeed show up in the FF download manager panel.

**Comment by shocked-gamer** [comment]
ok thank you, i asked cause i wanted to know if the translated string was correct.

**Comment by stephanmahieu** [comment]
Notice:
I will be dropping Korean when releasing the next version if the Korean translation remains incomplete.
Still missing 13 strings but the next release will require some additional Strings.
@limerainne ?

**Comment by limerainne** [comment]
Sorry for seriously late.
Please find my PR. Thanks :)

**Comment by stephanmahieu** [comment]
Merged into v2.5.7.1, released 18 October.
