### ISSUE TITLE
Settings for shortcuts are not remembered

### ISSUE THREAD

**Issue by lysathor** [stephanmahieu/formhistorycontrol-2#117]
**Describe the bug**
The setting if a shortcut is enabled is not stored.

**To Reproduce**
1. Open Settings (via addon page) and disable the shortcuts.
2. Press Apply.
3. Close the addon tab.
4. Open settings again (via addon page)
5. The setting is lost, all the shortcuts are enabled again.

**Expected behavior**
The settings should be remembered.

**Desktop (please complete the following information):**
 - OS: Win 10 x64
 - Browser Firefox
 - Version 82.0.3

**Comment by stephanmahieu** [comment]
On the Same OS and FF version I can not reproduce this. Can you try in a fresh/new profile?

**Comment by stephanmahieu** [comment]
Got no response from @lysathor and received no similar reports or issues.
Closing this issue.
