### ISSUE TITLE
Context menu should allow to select the text.

### ISSUE THREAD

**Issue by lysathor** [stephanmahieu/formhistorycontrol-2#118]
**Is your feature request related to a problem? Please describe.**
Yes. It is very coplicated to enter the desired text into the textfile.

**Describe the solution you'd like**
Show text options in the context menu.
Current solution is: Open window with all the form history. Select the field, copy the text and paste it manually. That is not very convenient.

**Describe alternatives you've considered**
At least show the text that will be inserted when I click "Fill fields with newest entries".

**Comment by stephanmahieu** [comment]
Introduced in release 2.5.7.0 October 8, 2023.
The right-click context menu, when opened from within an input field will offer a list with only items for that field.
