### ISSUE TITLE
Make the search field wider, please

### ISSUE THREAD

**Issue by birdie-github** [stephanmahieu/formhistorycontrol-2#124]
For some reasons it's very narrow even on my 1440p monitor.

![search](https://user-images.githubusercontent.com/4958603/119831849-30315c80-beed-11eb-96c1-90fb11d88a92.png)

_! such a long string_ is getting truncated:

![search](https://user-images.githubusercontent.com/4958603/119832635-e5fcab00-beed-11eb-81de-764967baec0d.png)

**Comment by stephanmahieu** [comment]
Incorporated in release 2.5.8.0
