### ISSUE TITLE
Please make the add-on window "normal" as opposed to being on-top

### ISSUE THREAD

**Issue by birdie-github** [stephanmahieu/formhistorycontrol-2#126]
I'm not sure if it's possible so, sorry, if it's not and please close.

Currently if you open "Manage History" the add-on window will stay on top of the browser window and it becomes impossible to use both at the same time.

Please make it a normal window instead, so that I could e.g. put the add-on window behind the browser.

**Comment by shocked-gamer** [comment]
it is normal. i opened it and it didn't stay on top of the browser window. settings, manage history or any other window of the addon doesn't stay on top of the browser, i don't remember it ever had

**Comment by birdie-github** [comment]
In Fedora 33, XFCE, when the Manage History window is open, it will always be above the main Firefox window.

Also I cannot minimize it. I click the titlebar minimize button and nothing happens. Maximize/Restore and Close buttons work as expected.

**Comment by shocked-gamer** [comment]
my guess is this, since the extension is the same for all operating systems, then it must be either a xfce bug or a linux firefox bug. i'm using windows 10 and as i said above i don't have that issue.

**Comment by stephanmahieu** [comment]
Indeed, it does not stay on top when on windows os but I do see the issue on Debian. I will investigate this...

**Comment by stephanmahieu** [comment]
Looks like under windows a popup and a panel behave the same, maybe under linux the type panel gives the desired result.

**Comment by stephanmahieu** [comment]
Nope, even tried the detached_panel type, all types except "_normal_" result in a window that is always on top of the browser. Looks like under linux only the "_normal_" type results in a window that is not always on top which basically is just a standard browser window with toolbars and all.
So unless you have a multiple monitor setup (or move the panel to another virtual desktop) or lots of window real estate, this is very annoying indeed.  Unfortunately there is nothing I can do that make the popup window not always on top.

The question remains: is this a bug or just the way things are handled by the Linux OS? I am afraid it is not a bug. Note also that there is no distinction in behavior and looks between panel and popup and that the panel type is deprecated according to the chrome API.

see also:
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/CreateType
- https://developer.chrome.com/docs/extensions/reference/windows/#type-WindowType
