### ISSUE TITLE
Show the exact number of entries being deleted

### ISSUE THREAD

**Issue by birdie-github** [stephanmahieu/formhistorycontrol-2#127]
It would be great if the add-on specified the number of entries being deleted as it's easy to select something accidentally in the history, move away from the selection, add new entries and then delete everything by mistake.

So, change:

**Multiple items have been selected, delete ALL selected items?** 

to

**125 items have been selected, delete them ALL?**

**Comment by stephanmahieu** [comment]
Incorporated in release 2.5.8.0
