### ISSUE TITLE
The "Field name" entry is missing for CKE editor entries

### ISSUE THREAD

**Issue by birdie-github** [stephanmahieu/formhistorycontrol-2#128]
I wonder if you could somehow pick it up from the page DOM or if it's impossible use something like

"CKE:hostname" e.g. "CKE:website.com"

Thank you!

**Comment by stephanmahieu** [comment]
I can not make an exception if the editable filed happens to be a CKE type of field. The fieldname, if present, is used to restore fields. Also, editable fields are often part of a larger DOM structure, often have no name or ID, and sometimes can not even be distinguished from data already entered.
