### ISSUE TITLE
Single-line entries have no host

### ISSUE THREAD

**Issue by birdie-github** [stephanmahieu/formhistorycontrol-2#130]
I've noticed that my history is full of single-line entries which have no Host field saved/populated.

Even now I've created a number of bug reports here on github.com and the host field is empty for all of them.

![no-host](https://user-images.githubusercontent.com/4958603/119836856-97e9a680-bef1-11eb-9d8c-c1a8a4463559.png)

**Comment by birdie-github** [comment]
It's a dupe of #76

Could you please give a rationale for this decision? I find it counterintuitive.

**Comment by stephanmahieu** [comment]
SIngle line fields are very often re-occuring on other websites. Think of e-mail or address fields. These fields can be re-used on other websites. Thus for suggesting formhistory entries when start typing in a single line field the domain is of no use. This has always been the way Firefox stores formhistory and that is also the way I store it now using the same data-model as FF still uses today. The local storage system is also not very well suited for relational data (1:n relations).
_Older version of my add-on (pre webextension) deduced the domain of a single line fields where it was last used by comparing the last used date and the browser-history._
