### ISSUE TITLE
Is the database really cleaned up?

### ISSUE THREAD

**Issue by birdie-github** [stephanmahieu/formhistorycontrol-2#131]
My FHC-2 Firefox database now weighs around 10 megabytes while I have just 255 entries saved.

If I run sqlite3 on it I see:
```
SELECT COUNT(*) FROM object_data;
14730
SELECT COUNT(*) FROM index_data;
15500
SELECT COUNT(*) FROM unique_index_data;
14732
```

This doesn't seem right. Does FHC-2 really clean up (`VACUUM;`) its database?

**Comment by stephanmahieu** [comment]
Yes it cleans up its own stuff but is does not use sqlite!

Sqlite is no longer available for add-ons developers and add-ons have no access to sqlite databases (unless they incorporate their own drivers). So what sqlite is showing you is internal data maintained by FF itself that is not accessible to add-ons.

Add-ons nowadays (like mine) use the IndexedDB API. See: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API

**Comment by birdie-github** [comment]
@stephanmahieu 

So how would I go about cleaning the database? I'm not a fan of 10MB of data stored on my disk when there's maybe 500KB actually used.

**Comment by stephanmahieu** [comment]
As mentioned before, add-ons do not use sqlite anymore, they can use IndexedDB which is not sqlite. Data in IndexedDB is not stored in sqlite databases and can be viewed with FF developer tools (Storage tab).
So ask Mozilla about sqlite. I do not know what exactly is inside all of these sqlite databases, wether the data is used or not, or if a simple vacuum would reclaim much of the unused space.
