### ISSUE TITLE
Add option to hide icon from URL bar

### ISSUE THREAD

**Issue by Joan** [stephanmahieu/formhistorycontrol-2#133]
The 3-dots menu has been removed from the URL bar since the last Firefox update (89). Now, the FHC icon appears directly in the URL bar.
It would be greate to have an option to hide it from there.

**Comment by justsome12** [comment]
any progress on this?

**Comment by stephanmahieu** [comment]
I have been very busy with a hardware project (house renovation) and my partner was experiencing some health issues, luckily both have been resolved recently and now I am enjoying a much needed vacation. I will pickup development some time after the summer has ended.

**Comment by Joan** [comment]
No rush though, it's easily hideable with userChrome.css and `.urlbar-addon-page-action {display: none;}` (disabling all url-bar ext) 🙂

**Comment by justsome12** [comment]
> No rush though, it's easily hideable with userChrome.css and `.urlbar-addon-page-action {display: none;}` (disabling all url-bar ext) 🙂

this also hides geotools though.

**Comment by Joan** [comment]
Yep, all URL-bar extensions, as specified 😌 I've edited the above comment with a FHC specific line.

**Comment by stephanmahieu** [comment]
Option to hide the address bar icon has been added to release 2.5.7.0.
