### ISSUE TITLE
FHC is shown to the right of the adress bar. very annoying had to deactivate it. 

### ISSUE THREAD

**Issue by justsome12** [stephanmahieu/formhistorycontrol-2#134]
FHC is shown to the right of the address bar. very annoying had to deactivate it. 2.5.6.1 - 89.0.1 (64-bit)

**Comment by shocked-gamer** [comment]
this has already been reported and acknowledged by Stephan in this report
https://github.com/stephanmahieu/formhistorycontrol-2/issues/133
