### ISSUE TITLE
Support for "select", "checkbox" and "radio"

### ISSUE THREAD

**Issue by Iey4iej3** [stephanmahieu/formhistorycontrol-2#138]
Currently, only textual inputs are supported. I propose to include select, checkbox and radio. [Here](https://www.tohodo.com/autofill/form.html) are some examples.

**Comment by stephanmahieu** [comment]
Select, checkbox and radio is supported but they can not be edited or exported/imported. When filling in forms (most used or most recent) these inputs will be restored as well (provided they where stored earlier).

**Comment by HanzCEO** [comment]
As of today, this doesn't work @stephanmahieu

**Comment by HanzCEO** [comment]
Weird that it's actually working again.
