### ISSUE TITLE
Exporting does not prompt for a file to save to

### ISSUE THREAD

**Issue by madduck** [stephanmahieu/formhistorycontrol-2#145]
**Describe the bug**
Trying to export all data, I get the spinner while the data are being collected, but then no file browser pops up, and the data cannot actually be saved anywhere.

**To Reproduce**
1. Click "Manage History" → File → Export
2. Click "Export"
3. Wait till the data are collected

**Expected behavior**
The docs suggest a file browser should open. It does not, and there is also no other way to specify the filename, and no file to be found.

**Desktop (please complete the following information):**
 - OS: Debian
 - Browser Firefox 99

**Comment by stephanmahieu** [comment]
Which desktop environment are you using, gnome?
