### ISSUE TITLE
blacklist

### ISSUE THREAD

**Issue by bill-hudacek** [stephanmahieu/formhistorycontrol-2#147]
I'm a user of 'cronometer'. URL https://cronometer.com/ - it's a good app on a phone, but the web site is *exceptional*.

Using the site requires frequent small text inputs to find recipes, add food to the 'diary', etc. Oddly, the text inputs are recorded BUT the URL is empty/blank/?.

So blacklisting does not work. I'd be happy to help you test this out. Else my history will be infested with things I can't find using a search - and history management would be a PITA. (I will never get close to 2500, I'm a list pruner...).

Testing your extension now, if it can fill an entire form instead of having to mouse-click for each.and.every.field as I move through a form, _**I'll send you $$**_. Promise. I miss Lazarus :-/

But it would be great to make this annoyance "go away".

**Comment by stephanmahieu** [comment]
Are these standard input fields? See #152

**Comment by stephanmahieu** [comment]
No response, question answered by #152 ?
