### ISSUE TITLE
Websites do not explicitly link this repository

### ISSUE THREAD

**Issue by the-moog** [stephanmahieu/formhistorycontrol-2#151]
**Describe the bug**

The project websites:
- [https://formhistory.blogspot.com](https://formhistory.blogspot.com)
- [https://stephanmahieu.github.io/fhc-home](https://stephanmahieu.github.io/fhc-home)

Do not explicitly link to the github project.  There is a tiny github logo at the bottom of one of the pages, but it's not that obvious.

**To Reproduce**
1. Go to either website
2. Look for the words Contribute or Developer or Issue tracker

**Expected behavior**
Clear link between website and github repo or users will find it tricky to understand the nature of the project, validate the intent and content and make contributions.

**Screenshots**

**Desktop (please complete the following information):**
 - Any
 - Firefox
 - Above Websites on 2 May 2023

**Smartphone (please complete the following information):**
 - n/a (Not tried)

**Additional context**
n/a

**Comment by stephanmahieu** [comment]
Users that are capable of understanding  (javascript) code should have no trouble spotting the github logo and immediate understand what it stands for. That being said it might be a good idea to add additional info on the website perhaps even in the menu.

**Comment by stephanmahieu** [comment]
Added a project page on github pages with references to GitHub plus more info and added a GitHub.com Project link to the blog
