### ISSUE TITLE
Formhistorycontrol shows text but copies text with HTML from tweets. 

### ISSUE THREAD

**Issue by victor-50** [stephanmahieu/formhistorycontrol-2#155]
When you hover over an entry from a tweet-form you see the text you entered. When you copy and paste the text a lot of html code is included (is this a bug or feature request? :-) ) I copied the text with html here, but it shows text only, so I attached the text with code. 

<div data-contents="true"><div data-rbd-draggable-context-id="0" data-rbd-draggable-id="en9gr"><div class="" data-block="true" data-editor="ek6mh" data-offset-key="en9gr-0-0"><div data-offset-key="en9gr-0-0" class="public-DraftStyleDefault-block public-DraftStyleDefault-ltr"><span data-offset-key="en9gr-0-0"><span data-text="true">A must-read on the replacement of human society by a transhumanist elite and AI. </span></span><span style="color: rgb(29, 155, 240);"><span data-offset-key="en9gr-1-0"><span data-text="true">@cor</span></span></span></div></div></div><div data-rbd-draggable-context-id="0" data-rbd-draggable-id="8clu5"><div class="" data-block="true" data-editor="ek6mh" data-offset-key="8clu5-0-0"><div data-offset-key="8clu5-0-0" class="public-DraftStyleDefault-block public-DraftStyleDefault-ltr"><span data-offset-key="8clu5-0-0"><span data-text="true"> </span></span></div></div></div><div data-rbd-draggable-context-id="0" data-rbd-draggable-id="1qnt2"><div class="" data-block="true" data-editor="ek6mh" data-offset-key="1qnt2-0-0"><div data-offset-key="1qnt2-0-0" class="public-DraftStyleDefault-block public-DraftStyleDefault-ltr"><span data-offset-key="1qnt2-0-0"><span data-text="true">"Increasingly the very idea of family is under assault, particularly from  universities and media that openly criticize monogamy and the nuclear  family"</span></span></div></div></div><div data-rbd-draggable-context-id="0" data-rbd-draggable-id="dk0eo"><div class="" data-block="true" data-editor="ek6mh" data-offset-key="dk0eo-0-0"><div data-offset-key="dk0eo-0-0" class="public-DraftStyleDefault-block public-DraftStyleDefault-ltr"><span data-offset-key="dk0eo-0-0"><br data-text="true"></span></div></div></div><div data-rbd-draggable-context-id="0" data-rbd-draggable-id="876g7"><div class="" data-block="true" data-editor="ek6mh" data-offset-key="876g7-0-0"><div data-offset-key="876g7-0-0" class="public-DraftStyleDefault-block public-DraftStyleDefault-ltr"><span style="color: rgb(29, 155, 240);"><span data-offset-key="876g7-0-0"><span data-text="true">https://www.zerohedge.com/technology/woe-humanity-how-ai-fits-broadly-rising-anti-humanism</span></span></span><span data-offset-key="876g7-1-0"><span data-text="true"> </span></span></div></div></div></div>

[tmp.txt](https://github.com/stephanmahieu/formhistorycontrol-2/files/12135953/tmp.txt)

**Comment by stephanmahieu** [comment]
Basically this extensions tries to find editable html elements on a page where content changes when the user types some text. The text may be displayed with formatting like bold or italic managed by javascriptr on that page and can be considered as a kind of wysiwyg editor. The "text" content of such html elements may therefore contain html tags managed by javascript on that page. The Formhistorycontrol extension has no knowledge of how the content is manipulated, it simply records the changes which may include html tags.

To answer your question, this is neither a bug nor a feature. Unfortunately there is nothing much we can do about that.
