### ISSUE TITLE
Remove icon from URL bar on Firefox

### ISSUE THREAD

**Issue by GameSpirit94** [stephanmahieu/formhistorycontrol-2#156]
Hi,

Form History Control is an essential extension for me, so first of all : thank you.
My main browser is Firefox, and I also use Chrome, and I just want to ask if the extension can be as invisible on Firefox as it is on Chrome, what I mean is : can I have a box to check on Firefox to hide the icon extension that constantly appears in the URL bar ? It shows there by default and I can't find an option to disable it.

Thank you.

**Comment by stephanmahieu** [comment]
It will be in the upcoming release very soon.

**Comment by stephanmahieu** [comment]
Duplicate of #133

**Comment by GameSpirit94** [comment]
Thank you !
