### ISSUE TITLE
Content script logs message to console, errors upon right click

### ISSUE THREAD

**Issue by mz8i** [stephanmahieu/formhistorycontrol-2#157]
**Describe the bug**

1. The extension's content script logs debug messages to console. This shouldn't be the case.
2. There is an error upon right-click context menu being opened.

See log below:

```
Showing menu... [collectFormData.js:1070:13](moz-extension://42e5b7f8-a747-4bf9-829d-7b366a653c02/content/collectFormData.js)
Showing menu for nodeName  canvas [collectFormData.js:1078:13](moz-extension://42e5b7f8-a747-4bf9-829d-7b366a653c02/content/collectFormData.js)
TypeError: elem.ownerDocument is null[collectFormData.js:1094:18](moz-extension://42e5b7f8-a747-4bf9-829d-7b366a653c02/content/collectFormData.js)
```

**To Reproduce**
1. Open developer console (F12)
2. Right click anywhere on any website
4. Debug logs and error log will appear

**Expected behavior**
Extension doesn't log anything at all to console and doesn't error.

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser: Firefox
 - Version: 2.5.7.0

**Comment by stephanmahieu** [comment]
Fixed in v2.5.7.1, released 18 October.
