### ISSUE TITLE
Automatically save text fields from pdf forms displayed by the pdf viewer

### ISSUE THREAD

**Issue by thx1111** [stephanmahieu/formhistorycontrol-2#163]
Currently, formhistorycontrol-2 fails to automatically save text fields from pdf forms displayed by the Firefox default pdf viewer.

Of course, automatically saving text fields from pdf forms would be very desirable.

It is possible to manually save a pdf form, including its text field entries, but this manual process does not provide for disaster recovery.

**Comment by stephanmahieu** [comment]
Yes that would be nice, however the content script provided by the extension is not loaded when viewing a pdf. So it looks like there is no way for any extension to access the DOM and extract data or attach event handlers. I believe Mozilla restricts access to the pdf/DOM when using the built-in pdf viewer.
Tested with http://foersom.com/net/HowTo/data/OoPdfFormExample.pdf

_As a side note: the DOM is loaded by the browser and can be viewed and manipulated with the developer tools.._
