### ISSUE TITLE
Publicly archive the old addon repo and rename this one?

### ISSUE THREAD

**Issue by YousufSSyed** [stephanmahieu/formhistorycontrol-2#165]
When I searched ["Firefox Form History Control"](https://www.google.com/search?client=firefox-b-1-d&q=firefox+form+history+control) I got the link to the old repo: https://github.com/stephanmahieu/formhistorycontrol-2. So I think you should do the following:
* Rename the repo to something like "Old Form History Control"
* Publicly Archive it
* Add a notice that it's be succeeded and link the new repo.

**Comment by stephanmahieu** [comment]
Added a notice.
Some people actually still use the old add-on it in older versions of FF or other Mozilla based browsers, so I will not archive the old repo for now.

**Comment by YousufSSyed** [comment]
@stephanmahieu 
- The repo hasn't been updated since 2016, couldn't u archive the repo but keep the addon in the store? 
- How do you measure active users? The Firefox addon store shows total downloads.
- Archiving would show a banner at the top and users wouldn't mistaken it for the current version.
