### ISSUE TITLE
Addon generally takes a very long time to load.

### ISSUE THREAD

**Issue by YousufSSyed** [stephanmahieu/formhistorycontrol-2#166]
On Firefox on my M1 MacBook Pro it takes a good 15 - 30 secs to load. The loading animation blocks the whole UI so I can't open the addon in a new window or open the settings until it finishes. It seems very unoptimized. Though it says I have 6000 results. If that's too much then maybe load them incrementally instead of all at once?

**Comment by shocked-gamer** [comment]
i just noticed this post, 6000 entries are way way too much, if you don't need them you should delete most of them.

**Comment by stephanmahieu** [comment]
The data is loaded dynamically by a jQuery plugin that this add-on relies upon. Maybe there is another way to use this plugins api but that would require a fundamental change. Your best option is to reduce the amount of entries.
