### ISSUE TITLE
Add a setting to open the addon in a new tab by default.

### ISSUE THREAD

**Issue by YousufSSyed** [stephanmahieu/formhistorycontrol-2#168]
The addon is very laggy and I don't want to have to wait for it to load. **If I click anywhere while the floating UI is open then it goes away.**

**Comment by shocked-gamer** [comment]
the floating UI isn't going away, it simply goes behind the browser window. unless you found some rare bug. as for the lag, how many entries do you have stored? if they are more than 1000, it's normally to take time to load them all.

**Comment by YousufSSyed** [comment]
I'd still like to just have it open in a new tab and wait for it to finish loading.

**Comment by stephanmahieu** [comment]
This add-on is designed as a popup dialog. It must be either a dialog or a browser tab, it can not do both, its a browser restriction.
