### ISSUE TITLE
Is the Project Dead ?

### ISSUE THREAD

**Issue by spacecabbie** [stephanmahieu/formhistorycontrol-2#177]
Just wondering if I should start to look for alternative.

**Comment by stephanmahieu** [comment]
No its not dead, just some private issues that take up all my spare time...

**Comment by spacecabbie** [comment]
> No its not dead, just some private issues that take up all my spare time...

Ah sorry to hear that, thanks for the update. Loving the addon thanks for clarrifing up to you to close this or keep open for others to see.
