### ISSUE TITLE
Question about confusing description about empty formhistory

### ISSUE THREAD

**Issue by JobLeonard** [stephanmahieu/formhistorycontrol-2#18]
> This add-on now uses the new mandatory WebExtensions API which no longer offers access to Firefox's built-in formhistory database. This means that after installing the WebExtensions enabled version, you start with an empty formhistory dataset.

I _think_ this means that you won't save the history from the previous version of the extension, but as it is written it can also be read as stating that installing this extension wipes the _Firefox_ form history database (so previously entered passwords and logins). I would be hesitant to install it if it would do that. Perhaps this wording would be more clear? (emphasized the changed part)

> This add-on now uses the new mandatory WebExtensions API which no longer offers access to Firefox's built-in formhistory database. This means that after installing the WebExtensions enabled version, _**the extension**_ starts with an empty formhistory dataset.

**Comment by JobLeonard** [comment]
PS: while I'm here, small error:

> This plugin stores text from text-fields and editor fields as you type, so you never have to *loose* your work when disaster strikes.

Struck by the classic "loose" vs "lose" typo ;)

Anyway, thanks for this add-on!

**Comment by shocked-gamer** [comment]
as for the 1st post, the developer means that after installing the addon, you won't be able to read/save the data from the Firefox form history feature. the addon doesn't delete anything.

**Comment by JobLeonard** [comment]
I understand, I'm merely pointing out that the text is a little bit ambiguous and that it doesn't hurt to fix it. I'm thinking of my mom who is afraid to install any add-ons that she doesn't fully understand because it might break her Firefox

**Comment by shocked-gamer** [comment]
don't worry, she can install it with no fear

**Comment by JobLeonard** [comment]
You're not getting my point.

**Comment by shocked-gamer** [comment]
and if anything goes wrong, before installing anything, do a backup of the folder located in this route.
C:\Users\[the username of the account]\AppData\Roaming\Mozilla

copy everything to a another folder and if something goes wrong, copy them back and all will be ok.

**Comment by JobLeonard** [comment]
I really appreciate that you are trying to help, but you misunderstood what I meant! :)

When I design a web-page or an application, I try to think "would my mother be able to figure this out?" to overcome my own biases of knowing how computers work.

My mother is just a concrete "stand in" for the less confident and tech-savvy users of computers. Trying to imagine how she might get lost or feel insecure is easier for me than thinking in abstract terms like "is this accessible to the less tech-savvy?" 

That little line is a little example of how ambiguity like this can scare the less technologically confident away. It seems trivial to us, but we're not the people we have to worry about.

**Comment by stephanmahieu** [comment]
How about this:

> This add-on now uses the new mandatory WebExtensions API which no longer offers access to Firefox's built-in formhistory database. This means that after installing the WebExtensions enabled version, you start with a secondary and initially empty formhistory dataset.

**Comment by shocked-gamer** [comment]
oh sorry, i thought that she was an average internet user and feared she might lost her FF form history.  👍

**Comment by JobLeonard** [comment]
No worries, your intentions were right :)
