### ISSUE TITLE
Where's the WIP branch code of this WebExtension?

### ISSUE THREAD

**Issue by timofonic** [stephanmahieu/formhistorycontrol-2#20]
Hello. 

I see the code in this Git repo hasn't been updated for months, but toy replied in a addons.mozilla.org review that this extension is srill in active development. 

Where's the code? Is it public?

If it isn't pubic...
Why not? Release early, release often ;)

Kind regards!

**Comment by stephanmahieu** [comment]
Well, indeed i am very busy with my real life, both on the job (where we do release often) and in my spare time.
The current wip is on my local (uncommited) branch. Be patient, there is a new release upcoming very soon.
