### ISSUE TITLE
Translation for options dropdowns possible?

### ISSUE THREAD

**Issue by proxymus** [stephanmahieu/formhistorycontrol-2#22]
I've noticed that there is currently no translation for the two display settings in the options dialog. Would it be possible to create one? It is currently hard coded in the popup\options\options.html file in the lines

64: <option value="default">default</option>
and
71: <option value="automatic">automatic</option>

![grafik](https://user-images.githubusercontent.com/1539498/44090825-c4b5a9e0-9fcb-11e8-994d-33304e5db48d.png)

**Comment by stephanmahieu** [comment]
Yes it is possible and I already fixed it.
