### ISSUE TITLE
Hard-coded multiline entry settings don't save enough entries, resulting in data loss

### ISSUE THREAD

**Issue by laniakea64** [stephanmahieu/formhistorycontrol-2#26]
Regarding this code -

https://github.com/stephanmahieu/formhistorycontrol-2/blob/98312645f325ce968c39b69dfb7d7027cef58870/background/receiveFormData.js#L706-L717

In Form History Control 1.4.0.6, the "10 min" and "500 chars" were configurable.  These hard-coded settings don't save enough editor history entries for my use, resulting in data loss.  As a test, I tried changing them locally to 1 min and 80 chars, and it worked much better.

Could you please make these settings configurable again?

Thanks!

**Comment by stephanmahieu** [comment]
It will be configurable in the next version.

**Comment by laniakea64** [comment]
Thanks for implementing this so fast! 😃  Testing latest git version and so far it looks good.

About number of characters, I looked up what I actually had set in Form History Control 1.4.0.6, and it was set at 75 characters.  This option is missing from the new drop-down.  I think I see how to add it, so I'll address this in a pull request.
