### ISSUE TITLE
Field Filter Not Working Properly v.2.1.0.1

### ISSUE THREAD

**Issue by 9jkh** [stephanmahieu/formhistorycontrol-2#29]
Continued from my EDIT in  "Not seeing cleanup option" issue #27, which you may not have seen:

Not seeing how to blacklist a field. Don't want text saved. Have entered both "message" and "textarea" in the Field Filter blacklist, and hit Apply, but neither removes saved item.

Thanks in advance for help or instructions to get this working.

Please see

https://s22.postimg.cc/dv5dexfht/FHC.png

https://s22.postimg.cc/pljaw1dch/FHC2.png

**Comment by stephanmahieu** [comment]
You have to use the exact name of the field you do not want to show up in your history. The field exclusion list will only prevent fields from being stored, it is not used in the cleanup operation which operates solely on date.
