### ISSUE TITLE
Allow to configure the auto-save interval (3-60 seconds)

### ISSUE THREAD

**Issue by birdie-github** [stephanmahieu/formhistorycontrol-2#39]
The said interval is now 5 seconds but I'd like to increase it to say each 30 seconds or decrease to 3 seconds. An option would be nice.

**Comment by stephanmahieu** [comment]
Why would you want to increase or decrease the auto-save interval?
Do you encounter data-loss or experience performance issues?

**Comment by stephanmahieu** [comment]
Now available in the 2.4.0.0 release
