### ISSUE TITLE
Very sluggish UI/100% CPU use on opening a window with saved entries (Linux Firefox 62.0.3 64)

### ISSUE THREAD

**Issue by birdie-github** [stephanmahieu/formhistorycontrol-2#40]
I open FHC-2 in an empty tab and one of my CPU cores becomes 100% busy. I have just a little over 100 entries in the databases, besides I just open the add-on window and doesn't do anything in it - it causes this CPU load just by being open.

![fhc-2](https://user-images.githubusercontent.com/4958603/46798518-93d1e000-cd6b-11e8-97e0-3bbfe1d9b76d.png)

**Comment by birdie-github** [comment]
I'm talking about the window which you open from Firefox add-ons panel (next to the address bar).

The "Manage History" window which is invoked by right mouse clicking works OK.

**Comment by stephanmahieu** [comment]
I also discovered earlier that (almost) the same javascript code seemed to cause a heavier load when opening the popup panel from the address-bar compared to opening the standalone window. It looks like the popup panel is given limited resources by the browser causing a heavier load for doing the same operation.

I will look into this again and try to get at the bottom of this.

**Comment by jayirvine** [comment]
I'm also seeing a massive slow-down when I start typing into a text field and it tries to offer me suggestions (which I don't want anyway, so doubly annoying) it will stop me from being able to type for a second or two. 

(Firefox on Mac)

**Comment by stephanmahieu** [comment]
There is an add-on preference in the Miscellaneous section, "_Override the built-in autocomplete_"

**Comment by stephanmahieu** [comment]
Should be fixed with the 2.4.0.0 release
