### ISSUE TITLE
No way to search to fill a particular version of the form

### ISSUE THREAD

**Issue by ReporterX** [stephanmahieu/formhistorycontrol-2#45]
I don't see there is any way to search a form to fill in. (Note: we are talking about the whole form, not just a particular textarea field). Opening up the history popup, it shows a lot of saved data in different text fields, but there is no way to find and restore a particular version of the form as a whole.

It would be great if there is a way to search and restore a particular version of the form at a particular link. 

Thank you.

**Comment by stephanmahieu** [comment]
Although this add-on offers some basic form filling functions, its main purpose is to save and restore data in case disaster strucks. If you need more advanced form filling features I suggest looking at other specialized add-on.
