### ISSUE TITLE
Character limit? Option to change.

### ISSUE THREAD

**Issue by mxmilkb** [stephanmahieu/formhistorycontrol-2#46]
Is there a character limit to what is saved? Some forms will also save html formatting, like posts on Gist, which makes their form content large. The limit on text means that there is a higher chance that only a partial form can be restored (after running the text through an html stripping tool). The ability to extend the size of the content saved for each form is really needed for such situations (I've just lost 2/3 of a document).

**Comment by stephanmahieu** [comment]
There really is not a hard coded character limit. It could be that there is some browser limit in what can be stored in he database or you might reach a maximum limit for the amount of data that can be sent from the page to the background process.

@mxmilkb  Can you tell me what the total amount of data is you tried to save with the form?

**Comment by stephanmahieu** [comment]
No response from issuer, unable to reproduce.
