### ISSUE TITLE
Select All does not respect search filter

### ISSUE THREAD

**Issue by codeman38** [stephanmahieu/formhistorycontrol-2#47]
In the full Manage History dialog, the "Select All" menu item does not behave as I would have expected when the results have been filtered by a search term. Rather than selecting only the matches that are visible, it selects the entire table, including those rows that have been filtered out.

I accidentally deleted my entire form history because of this - I had assumed that Select All would only select the rows for the specific field name I had searched for, and completely failed to notice that the "rows selected" count was greater than the (already large) number of matches shown.

**Comment by stephanmahieu** [comment]
Fixed and released, v2.3.0.1
