### ISSUE TITLE
UN-assign shortcuts

### ISSUE THREAD

**Issue by auralarch** [stephanmahieu/formhistorycontrol-2#48]
I can find no description of how to un-assign/remove a shortcut from an action, nor can I figure out any way to do so.   There is also no obvious/easy to find way to ask a question on the plugin's main page/site.

This ability/feature is important!  I may already have those shortcuts applied to other functions or may not wish to potentially be able to accidentally activate certain commands.
As you mentioned, there is not a mechanism to check for conflicts; nor is there any clearly defined system of which action will actually be triggered where there is a conflict.  In fact, my experiences have added to my confusion because one particular action is not always triggered over the other and it is unclear why the "winner" is the action that gets triggered.

The "obvious" (to me) solution would be the addition of a "--none--" (or "disabled", or something similar/synomymous) item to the list of keyboard keys.

Any thoughts, reactions, contradictions or ideas?

**Comment by stephanmahieu** [comment]
I must admit I am not happy myself about the way the shortcut keys are implemented by Mozilla/Chrome.
They must be specified in the manifest.json of the application. Unfortunately that means they must be predefined and must have a valid value (and none or disabled is not a valid state). You can alter the shortcut keys at startup of the add-on and change it to the users preference as I do, but still they must contain a valid key combination.
And the way it works is that the key combination is a suggestion to the browser and it is never certain if that suggestion is honored.
More info here: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands
