### ISSUE TITLE
not respecting autocomplete="off"

### ISSUE THREAD

**Issue by jayirvine** [stephanmahieu/formhistorycontrol-2#49]
The plug-in is saving values typed in to fields that have autocomplete="off" set (I've found passwords and other stuff in my history that shouldn't be there...)  I've checked with dev toolbar that autocomplete="off" is set for those fields.

**Comment by stephanmahieu** [comment]
I have explicitly chosen to save form history for fields that have autocomplete="off" set. So the short answer is: _works as designed_. I personally find it very annoying that these fields are not stored by default by the browser, so I have chosen to differ in that respect.
For password fields, inputs of type password should be used, and these fields will never be saved by my add-on.
