### ISSUE TITLE
Extreme Memory Leak Form History Control (II) dead14b7-e0fa-4a1c-862c-ee671bb77b49 

### ISSUE THREAD

**Issue by motiv8d** [stephanmahieu/formhistorycontrol-2#50]
Have identified a really bad memory leak with Form History Control (II) dead14b7-e0fa-4a1c-862c-ee671bb77b49 
It seems most noticeable when using Facebook and multiple tabs.
Something triggers, and I cannot say what, but when it does, this will steadily keep increasing RAM and VM usage. I have 16GB RAM on a Linux system on FF Quantum 66.0.5.
The system normally locks up completely when it has reached around 20GB. Close to this X is completely locked up. The most I have seen it reach is about 25GB while monitoring in a separate text terminal.  
The section in about:memory that increases is:
top(moz-extension://dead14b7-e0fa-4a1c-862c-ee671bb77b49/_generated_background_page.html, id=6442450952)

Uninstalling as this leak makes brings everything down.

**Comment by stephanmahieu** [comment]
I also use facebook but I do not recognize this problem nor am I able to reproduce this problem.
It would be most helpful if you can give me some more info on how to reproduce this. Does this happen when chatting or posting messages on the timeline? Or when adding photo's?

**Comment by stephanmahieu** [comment]
Unable to reproduce.
