### ISSUE TITLE
Store and select by hostname for all field types

### ISSUE THREAD

**Issue by richardb64** [stephanmahieu/formhistorycontrol-2#52]
Hi Stephan,

I just came across issue #6 from last year, which you closed because FHC is working in the same way as the default Firefox behaviour, ie. textarea fields store the associated hostname/URL, but other field types don't.

I have to agree with @jidanni - the behaviour of Firefox to offer auto-filled text between unrelated sites, just because the form name happens to be the same, has always annoyed me, especially as there seems to be no way to turn it off if I value privacy over convenience.  This is especially odd given Mozilla's stated goal of being the most privacy-conscious browser.

So I wonder: please can you reconsider letting FHC fill this gap in usability (and privacy), by storing the hostname and URL on _all_ fields, and always listing matching entries first when offering completions?  I think this was in fact the behaviour of the previous XUL version.  Similarly, the bulk "fill all fields" features should only ever fill in data previously entered on the _same_ site, though there could perhaps be a separate option to "fill in as much as possible from anywhere".  It's already possible to _deliberately_ choose to copy text entered on one site into another, but I never want the browser to do that by default.

**Comment by stephanmahieu** [comment]
> I think this was in fact the behaviour of the previous XUL version.

No it most definitly was not.

**Comment by stephanmahieu** [comment]
Associating each field with a host or URL has a considerable impact, especially since the underlying datastore is not a relational database. So to make this behavior optional is almost impossible, not doing so would affect all users.

Proposed change might be useful if this add-on was primarily a formfiller but it is not.
