### ISSUE TITLE
Only retain multi-line fields?

### ISSUE THREAD

**Issue by richb-hanover** [stephanmahieu/formhistorycontrol-2#53]
I love Form History Control. It has saved my neck many times because I got distracted, lost power, or otherwise screwed up while filling out a form.

But I was surprised (I shouldn't have been, but I was anyway) to see things like my credit card number, CVV code and public & private API keys in its history. 

I propose the following configuration option: **Only retain multi-line fields.** (This might be a checkbox in the Field Filter pane.)

This would allow me to recover the long essays that I have typed into web forms while ignoring all the single-line fields that my browser remembers anyway, fields that I know by heart, or fields with data that I store in my password manager (and don't want saved elsewhere). 

(As an alternative, I could live with a wildcard in the Field Filter entries, so I could add entries like this: \*ccard\*, \*cvv\*, \*private\*, \*public\*, etc.) Many thanks for a great tool.

**Comment by stephanmahieu** [comment]
You can now choose what type of fields should be saved in the 2.4.0.0 release

**Comment by richb-hanover** [comment]
Got it! Thanks!
