### ISSUE TITLE
Fill fields with saved plain text (remove HTML etc)

### ISSUE THREAD

**Issue by businessBoris** [stephanmahieu/formhistorycontrol-2#54]
Had your extension installed for, probably, years now.  First time I remember using it!
It's rather lovely!
I got caught though: when restoring a Reddit post it posts the HTML too which Reddit won't allow me to edit.
Is there, can there be, an option to provide plain-text only please; just the text not the html formatting?

**Comment by stephanmahieu** [comment]
From the menu or dropdown menu you currently can only copy all, but if you open the saved item you can right-click inside the popup window and you will be presented with two options of which one will allow you to copy the plain text without the formatting.
