### ISSUE TITLE
Makes the fan spin on Firefox/Mac OS X

### ISSUE THREAD

**Issue by l-g** [stephanmahieu/formhistorycontrol-2#57]
Every half hour or so FHC runs wild on my machine and makes the fans spin at max. Disabling/enabling it fixes it for a while and then it happens again.

I have a lot of tabs open, including Facebook.

Looking in Activity Monitor, one of the FirefoxCP WebExtension processes uses a lot of CPU, 30-40 %, even if Firefox is idling in the background, which in turn makes the main Firefox process run at maybe 150 % CPU (this is on an i7 with 4+4 cores). Waiting ten minutes for it to finish whatever it is doing doesn't help.

(Beyond disabling/enabling I can also kill the Firefox CP WebExtension process but then a lot of other extensions are disabled too).

Let me know if I can provide you with some more details about this.

I reckong this has been going on for a couple of months.

**Comment by stephanmahieu** [comment]
Might be related to issue #36. Can you disable the Automatic Cleanup option (see [manual](https://stephanmahieu.github.io/fhc-home/Manual/manual/#clean-up)) and see if this prevents the excessive CPU utilization every half hour?

**Comment by stephanmahieu** [comment]
Should be fixed with the 2.4.0.0 release

**Comment by stephanmahieu** [comment]
I identified another possible cause for the increase in CPU utilization. It has to do with preparing the context-menu beforehand. If this is somehow triggered for each opened tab in the browser the OS can become very busy, especially with many tabs open.
Starting with release [2.5.7.0](https://stephanmahieu.github.io/fhc-home/ReleaseNotes/fhc-releasenotes/#2570-october-8-2023) the context-menu is constructed upon use only.
