### ISSUE TITLE
View all

### ISSUE THREAD

**Issue by wargo32** [stephanmahieu/formhistorycontrol-2#58]
Not possible to view more history. Message says: "open the advanced 'Manage History' window (right mouseclick)" but not tells where to click by right button.

**Comment by stephanmahieu** [comment]
Right-click on the icon in the menubar, choose the first item.

**Comment by gpz1100** [comment]
Is this still valid?

Icon in what toolbar, where?

Clicking the icon in the form history control diag box next to the X (top right), opens another dialogue box but still presents the same error.
