### ISSUE TITLE
Added Russian language files

### ISSUE THREAD

**Issue by wvxwxvw** [stephanmahieu/formhistorycontrol-2#61]
Only I have why the field have diverged on different lines. If you can fix it. What would the search and "how many records to show" were on the same line. And in large and in small dialogue.
![2019 11 20_175644](https://user-images.githubusercontent.com/13194155/69249608-355a7080-0bbf-11ea-8412-5044c8ccedcf.png)
And still request not pull with merger. I am annoyed with temporary repositories and I will delete them sooner or later, whether they are used or not.
https://github.com/stephanmahieu/formhistorycontrol-2/pull/59#issue-343397488
https://github.com/stephanmahieu/formhistorycontrol-2/pull/60#issue-343398181

**Comment by stephanmahieu** [comment]
Very odd, I will look into this.

**Comment by wvxwxvw** [comment]
Not only that, there's something else skewed. Please release a new version. I apparently that is not so made, when building the extension.

**Comment by stephanmahieu** [comment]
Is the issue with fields on different lines only happening when using the Russian language?
Right now, with English or Dutch, everything looks okay.

**Comment by wvxwxvw** [comment]
I haven't checked with other languages. Now it is problematic for me to do it.

**Comment by stephanmahieu** [comment]
I will try to check if the problem is with Russian language only, maybe the length of one of translations is causing this. The problem could be in the third party lib (DataTables plugin).

**Comment by wvxwxvw** [comment]
The first thing I did was make the length everywhere (in windows) less than in the English version.
I think that I was mistaken when assembling somewhere. The options here and on AMO are different and I combined something there, because otherwise, Firefox did not accept the extension.

**Comment by stephanmahieu** [comment]
Now available in the 2.4.0.0 release
