### ISSUE TITLE
Add or improve exceptions by field type

### ISSUE THREAD

**Issue by wvxwxvw** [stephanmahieu/formhistorycontrol-2#62]
Very bad work exceptions. Let's go from the opposite. Make the option "textarea only" and a list of inclusions.

**Comment by stephanmahieu** [comment]
Are you referring to the field filter?

**Comment by wvxwxvw** [comment]
No. Exceptions to remember these fields, in the settings.

**Comment by stephanmahieu** [comment]
The new version will let you choose which fieldtype to retain

**Comment by wvxwxvw** [comment]
Exceptions all also don't work. Add to exceptions "div"
![2019 12 29_160231](https://user-images.githubusercontent.com/13194155/71557265-f12b7d00-2a54-11ea-9a06-a9eca1abf827.jpg)
and .... 
![2019 12 29_160109](https://user-images.githubusercontent.com/13194155/71557267-f688c780-2a54-11ea-8ac4-1e1948d9b430.jpg)

**Comment by stephanmahieu** [comment]
Exceptions only work for fieldnames not field-types (by design).

**Comment by wvxwxvw** [comment]
As you can see, not all fields have names. You may change this in future versions? Or add the possibility of exclusion by "site + field name (including the possibility of an empty name)", for example, codes with githab I do not need in memory at all.

**Comment by stephanmahieu** [comment]
Some html elements have neither a name nor an id. In that case the fieldname is empty.

**Comment by wvxwxvw** [comment]
I understand that, but this issue must be resolved. One way or another.

**Comment by stephanmahieu** [comment]
> this issue must be resolved. One way or another.

I disagree. Anonymous fields just exist and excluding all these might exclude too much fields you might be interested in.

**Comment by wvxwxvw** [comment]
How will this happen if exceptions are configured by "site + field name or type field"?

**Comment by stephanmahieu** [comment]
I have no intention in implementing an exclusion/filter/exception for fieldtypes. I see no problem in the way it currently works.
I could however add an exclusion based on site+field, maybe like so: `host:fieldname` but it wil only work for named fields.

**Comment by wvxwxvw** [comment]
At least that way. And placeholder for empty names you can not do?

**Comment by stephanmahieu** [comment]
> And placeholder for empty names you can not do?

In that case, how about: `host:<empty>`, and as an example: `github.com:<empty>`

**Comment by wvxwxvw** [comment]
Yes, as you wish, as long as it worked.

**Comment by stephanmahieu** [comment]
Now available in release 2.5.0.0.

**Comment by Nakonana** [comment]
@stephanmahieu sorry for posting on a closed issue, but I'm having the same problem. 
Most websites I use seem to have unnamed fields, so I can't really add a field filter other than `<empty>`. However, if I understand it right, `<empty>` will prevent all fields on a certain website/host to be recorded, which is problematic for me. So, basically my issue is that I want field-type x to be recorded, but not field-type y. As examples: Record `textarea` on `github.com`, but don't record `input` on `github.com`. Is there a way to do this? `github.com:<empty>` wouldn't work for me, right?

**Comment by stephanmahieu** [comment]
Specifying `github.com:<empty>` would prevent storing all anonymous (unnamed) fields of any type on github.com. You can not specify a certain type from being recorded on specific websites/hosts.
