### ISSUE TITLE
How to deinstall this addon

### ISSUE THREAD

**Issue by phu9Suop** [stephanmahieu/formhistorycontrol-2#64]
Hi Stephan
I use debian stable 10.2 and firefox-esr 68.3.0 from the distribution.
I miss the right click menu entry to cleanly deinstall the addon,  it has only deactivate option. 
best regards Erich

**Comment by stephanmahieu** [comment]
Hi Erich
Have you tried uninstalling using the Add-ons page: **_about:addons_**
If you click the 3 dots in the upper right corner you get the option to deactivate as well as uninstall.
