### ISSUE TITLE
Context menu item

### ISSUE THREAD

**Issue by wvxwxvw** [stephanmahieu/formhistorycontrol-2#68]
The context menu item appears anywhere on the page, please add the ability to completely disable it in the settings.

**Comment by stephanmahieu** [comment]
Don't know what you mean, it does only appear when you right-click does it?

**Comment by wvxwxvw** [comment]
Yes, but it appears anywhere, on links, pictures, etc. And I do not even need it on the page, but only in the editable field.

And it's not even about me, I'll hide it in style userChrome. It's about the friendliness of the interface.

Understand correctly. The author of each add-on, considers his add-on the most important and if everyone shoves the items of his add-on in the General context menu, there will be no space left for the really necessary items. Does your extension work with fields? Well, let its item be only in the context menu of fields.

**Comment by stephanmahieu** [comment]
See also my answer in #34.
I will look into a preference setting that for disabling the context menu.

**Comment by stephanmahieu** [comment]
Now available in release 2.5.0.0.
