### ISSUE TITLE
In Advanced History choose "Select All" then "Copy to Clipboard": only one item is copied

### ISSUE THREAD

**Issue by jidanni** [stephanmahieu/formhistorycontrol-2#7]
In Advanced History choose "Select All" then "Copy to Clipboard".

Only one item is copied to clipboard.

**Comment by stephanmahieu** [comment]
Right clicking always acts upon the (single) item that was clicked. Copying multiple items to the clipboard is not supported. That is also why the menu item is grayed-out when multiple items are selected.
(This will be clearly documented in the near future)

**Comment by jidanni** [comment]
All I know is on the menu,

    Add
    Modify
    Delete
    Copy to clipboard
    Select all
    Select none
    Invert selection

if I click "Select all",
"Copy to clipboard" does not become greyed-out.

Note: Yes, "Copy to clipboard" indeed does become grey, if we are
talking about the "Edit" menu's "Copy to clipboard". Alas, there is
another menu, the Right Click Menu. Here it doesn't become greyed-out.

Furthermore, in both the non-advanced form history control window, and
the advanced form history control window, such right click menus are
rather persistent. Not even disappearing when one clicks in various
blank areas of the screen. They seem to insist one click one of the
choices offered. Even ESC doesn't make them go away.
