### ISSUE TITLE
Disable history per domain should include subdomains

### ISSUE THREAD

**Issue by birdie-github** [stephanmahieu/formhistorycontrol-2#71]
I have wikipedia.org blacklisted thus I expect en.wikipedia.org to be blacklisted as well.

Please implement this feature or offer a way to blacklist all subdomains (and that might mean fourth level domains as well, e.g. aaa.bbb.domain.com)

Thank you!

**Comment by stephanmahieu** [comment]
Now available in release 2.5.0.0.
