### ISSUE TITLE
Cannot delete multiple entries via Right mouse click -> Delete

### ISSUE THREAD

**Issue by birdie-github** [stephanmahieu/formhistorycontrol-2#73]
Steps to reproduce:
1. Open Manage History
2. Select multiple entries
3. Right mouse click anywhere in the list
4. Click Delete

Result: only an entry right beneath the mouse cursor will be deleted
Expected result: all the selected entries are deleted

Note: Menu: Edit -> Delete works as expected

**Comment by stephanmahieu** [comment]
This actually how it is designed to work.

**Comment by birdie-github** [comment]
> This actually how it is designed to work.

This break all known conventions. ;-) What's the selection for then?

**Comment by stephanmahieu** [comment]
> What's the selection for then?

The buttons on the bottom (Add, Delete, Modify) and the Edit menu on top.

**Comment by stephanmahieu** [comment]
How about this solution:
- if one or more entries are selected, act upon the selection
- if nothing is selected act upon the right-clicked item

_For Copy to clipboard when multiple items are selected only the first selected item is copied._

**Comment by stephanmahieu** [comment]
Now available in release 2.5.0.0.
