### ISSUE TITLE
Ctrl + A in the Manage history list should select all the displayed entries

### ISSUE THREAD

**Issue by birdie-github** [stephanmahieu/formhistorycontrol-2#74]
Currently pressing Ctrl + A selects menu items and various other UI elements.

**Comment by stephanmahieu** [comment]
There was also a bug regarding the Alt-key shortcuts not working (key being the underlined characters in the context-menu)

**Comment by stephanmahieu** [comment]
Now fixed in release 2.5.0.0.

**Comment by wvxwxvw** [comment]
@stephanmahieu 
I have everything left as it was.
![gif337](https://user-images.githubusercontent.com/13194155/72196769-9407d200-342b-11ea-8315-8e67bb9a740b.gif)

**Comment by stephanmahieu** [comment]
Hmm, _works on my machine_.
Ctrl+A should not select all items in this list in this popup because you can select only 1 item but it should not highlight everything else.

Does it work in the the big popup window?

**Comment by wvxwxvw** [comment]
68.4.1 esr x64. It's the same in the big window. Right away I'll check it on a clean profile.

**Comment by birdie-github** [comment]
@wvxwxvw 

Works for me in the normal window - doesn't work in the popup window.

But then I'm running Firefox 72.

**Comment by wvxwxvw** [comment]
@birdie-github А вы? =)

**Comment by birdie-github** [comment]
Please stick to the English language and avoid offtopic comments. The author of this add-on doesn't have to handle SPAM in tickets.

**Comment by wvxwxvw** [comment]
@birdie-github 
Please avoid offtopic comments. The author of this add-on doesn't deserve and doesn't have to handle SPAM in tickets. Like your previous one, about the extension version.

**Comment by stephanmahieu** [comment]
Still can not reproduce this. Selected text is made invisible by manipulating the css style since the default behaviour can not be prevented.

I am running FF 72.0.1 (64 bit). Also with Quantum 73.0b3 (64-bits) no problem.

**Comment by stephanmahieu** [comment]
Aha, does not work on Debian with FF 68.3.0esr (64bit).

Okay, will try to fix...

**Comment by stephanmahieu** [comment]
Now fixed and available in v2.5.1.0

**Comment by wvxwxvw** [comment]
All OK.
