### ISSUE TITLE
Allow to manage columns/field in history

### ISSUE THREAD

**Issue by birdie-github** [stephanmahieu/formhistorycontrol-2#78]
It would be great to be able to show/hide individual columns/fields like Type/Count/First Used/Last used/etc. - pretty much all of them.

**Comment by stephanmahieu** [comment]
This is supported by the DataTables plugin used with the help of the [Buttons](https://datatables.net/extensions/buttons/built-in) plugin.

Also on my personal wishlist ;-)

**Comment by stephanmahieu** [comment]
Now available in release 2.5.0.0.
