### ISSUE TITLE
The addon popup window is resizable or not?

### ISSUE THREAD

**Issue by birdie-github** [stephanmahieu/formhistorycontrol-2#80]
Please make up your mind :-)

Currently the drag mouse cursor appears when you're hovering the lower part of the popup window (the one which appears when you click the addon icon in the Firefox toolbar) and you can kinda resize it a little bit and then you can't. It behaves in a very weird way.

**Comment by stephanmahieu** [comment]
Yeah, resizing the popdown-window is not (very well) supported by the Mozilla webextensions framework. The way it works now is as good as its gets. I have spent many hours to get it to the way it works now. I am not really happy with this but it is at least better than not being re-sizable at all.
