### ISSUE TITLE
Context menu to restore history of a unique field

### ISSUE THREAD

**Issue by ShareOut** [stephanmahieu/formhistorycontrol-2#81]
FHC is very useful for my CMS / server management by navigator work.

For this use case, it would be very useful to have a menu item like "Restore editor field" but which lists only the history of a single field (matching field name) and which only restores this field.

Thanks and have a happy new year

**Comment by dumblob** [comment]
I'd second this one. It's actually the most common scenario in my case - usually PC or web browser crashes (or is being inadvertently closed) and opens on the same page and I want to have a single-click recovery like e.g. Typio Form Recovery offers on Chrome (yes the recent versions of Typio Form Recovery **are** reliable and very user friendly).

**Comment by stephanmahieu** [comment]
Introduced in release 2.5.7.0 October 8, 2023.
The right-click context menu, when opened from within an input field will offer a list with only items for that field.
