### ISSUE TITLE
Russian translation needs update

### ISSUE THREAD

**Issue by stephanmahieu** [stephanmahieu/formhistorycontrol-2#82]
I have added the following strings that need translation:
```
XXXfieldLength
XXXbuttonColumnVisibility
XXXbuttonRestoreColumnVisibility
XXXoptionsContextMenuSelect
XXXoptionContextMenuPage
XXXoptionContextMenuEditfields
XXXoptionContextMenuNone
```

Please translate from English to Russian and remove the XXX prefix. (@wvxwxvw ?).

**Comment by wvxwxvw** [comment]
In the case of the Russian language, you can simply not add new lines to the file, but inform about the need for translation. When translating, I always focus on the English file and take the missing lines from it.

I'll make a request now.

**Comment by stephanmahieu** [comment]
Okay, and thanks for the PR.
