### ISSUE TITLE
Korean translation needs update

### ISSUE THREAD

**Issue by stephanmahieu** [stephanmahieu/formhistorycontrol-2#83]
I have added the following strings that need translation:
```
XXXfieldLength
XXXbuttonColumnVisibility
XXXbuttonRestoreColumnVisibility
XXXoptionsContextMenuSelect
XXXoptionContextMenuPage
XXXoptionContextMenuEditfields
XXXoptionContextMenuNone
```

Please translate from English to Korean and remove the XXX prefix. (@limerainne ?)

**Comment by limerainne** [comment]
Please accept PR #87 which adds translated strings for above new strings.

**Comment by stephanmahieu** [comment]
Thank you for the translation 👍
