### ISSUE TITLE
Greek translation needs update

### ISSUE THREAD

**Issue by stephanmahieu** [stephanmahieu/formhistorycontrol-2#84]
Since the last Greek translation, many new strings have been added.
All strings with a XXX prefix need translation from English to Greek.
@shocked-gamer ?

```
XXXfieldLength
XXXbuttonColumnVisibility
XXXbuttonRestoreColumnVisibility
XXXoptionsExpertMode
XXXoptionsScrollAmountSelect
XXXoptionsContextMenuSelect
XXXoptionContextMenuPage
XXXoptionContextMenuEditfields
XXXoptionContextMenuNone
XXXoptionsOverrideIncognito
XXXoptionsRetainFieldTypes
XXXoptionsRetainFieldAll
XXXoptionsRetainFieldMulti
XXXoptionsRetainFieldSingle
XXXoptionsuUdateInterval
```

**Comment by GregB712** [comment]
Hello, I would like to help in the greek translation.

**Comment by stephanmahieu** [comment]
Hi @GregB712 , if you would like to help please fork this project, make adjustments and create a pull request.

@shocked-gamer informed me that he was going to help too but he has no computer at the moment and was planning to make his changes at his next visit to the internet café so your help would be much appreciated.

**Comment by GregB712** [comment]
I created the pull request, waiting feedback. Pull request here -> #86

**Comment by stephanmahieu** [comment]
Looks good to me.
Thanks Greg.
