### ISSUE TITLE
No horizontal scroller for the manage history list

### ISSUE THREAD

**Issue by birdie-github** [stephanmahieu/formhistorycontrol-2#88]
Looks like you've added new columns in the latest release (2.5) and I don't see them unless I maximize the add-on window.

Please add a horizontal scroller if some columns don't fit the current view.

**Comment by stephanmahieu** [comment]
If the width of the view is too small to fit all columns, low priority columns are not shown. My advice is to either turn off columns you do not want to see or are less important to you or stretch the view as wide as possible.
Unfortunately the datatable component used does not support a horizontal scrollbar in a satisfactory manor with respect to responsive behaviour.
