### ISSUE TITLE
Wildcard support for domain blacklisting/whitelisting needs an explanation

### ISSUE THREAD

**Issue by birdie-github** [stephanmahieu/formhistorycontrol-2#89]
You've added support for using wildcards for domains blacklisting/whitelisting but I've idea how to use it. Could you add an explanation please?

To disable wikipedia.org and **all** its subdomains, should I blacklist

`wikipedia.org`
or
`*.wikipedia.org`
or
`wikipedia.org` and `*.wikipedia.org`
or 
`*wikipedia.org` (but will that mean abcwikipedia.org will match as well? That's not right - it's a different domain)
or
`wikipedia\.org` and `.*\.wikipedia\.org` (in case it's a regexp)?

**Comment by stephanmahieu** [comment]
It is described in the manual (See Help overview from context menu or add-on menu) for both the [Domain](https://stephanmahieu.github.io/fhc-home/Manual/manual/#domain-filter) Filter as well as the [Field filter](https://stephanmahieu.github.io/fhc-home/Manual/manual/#field-filter).

**Comment by stephanmahieu** [comment]
And to answer your question: to blacklist wikipedia.org and all its subdomains: `*wikipedia.org`

**Comment by birdie-github** [comment]
> And to answer your question: to blacklist wikipedia.org and all its subdomains: *wikipedia.org

That has an intended effect of matching any domain which ends with wikipedia.org, e.g. it's easy to image a user entering this mask:

`*le.com`

And then having troubles with examp**le.com**

**Comment by birdie-github** [comment]
To avoid any issues, I guess I have to enter:

`wikipedia.org`
and
`*.wikipedia.org`

Correct?

**Comment by stephanmahieu** [comment]
_With great power comes great responsibility_ :-)

That is also why it is now under the Advanced options.

**Comment by birdie-github** [comment]
To avoid any issues, I guess I have to enter:

`wikipedia.org`
and
`*.wikipedia.org`

Correct?
