### ISSUE TITLE
Add "Export to File"

### ISSUE THREAD

**Issue by jidanni** [stephanmahieu/formhistorycontrol-2#9]
The Export Download link is a data string.
99% of users are used to exporting to a file. Please add that too.
Most users will end up pasting the mile long data string into their terminal etc. (4th of July effect.)

**Comment by stephanmahieu** [comment]
Directly exporting to a file is not supported by the Mozilla API. This is the next best thing.

**Comment by jidanni** [comment]
OK but do consider putting some tips next to the link that appears,
as surely 99% of users have never encountered this type of Download.
