### ISSUE TITLE
Expand the search field in the main history window

### ISSUE THREAD

**Issue by wvxwxvw** [stephanmahieu/formhistorycontrol-2#94]
Increase the length of the search field in the main history window. This is the third time I've written, and maybe you won't forget it now. =)

**Comment by stephanmahieu** [comment]
Noted, I thought it was resolved when you adapted the translation. I figured the box was large enough to accommodate all languages.
I guess the translation of "_Search..._" for some languages is rather large.

**Comment by wvxwxvw** [comment]
It is solved in a small window, and in the big all as well.
There is a lot of space and a small string just looks ugly.

**Comment by stephanmahieu** [comment]
Released with FHC version 2.5.3.1
