### ISSUE TITLE
Error filling in the input field in the exception list

### ISSUE THREAD

**Issue by wvxwxvw** [stephanmahieu/formhistorycontrol-2#95]
I don't know if it's a bug or a feature.
The add button is not active when inserting, but it is activated after manual input.

![gif337](https://user-images.githubusercontent.com/13194155/72196146-4c7f4700-3427-11ea-8cf9-7b66cf7581b3.gif)

**Comment by stephanmahieu** [comment]
I would call that a bug, when text is pasted the button should become active. I have overseen this possibility.

**Comment by stephanmahieu** [comment]
Does works with Ctrl+V but not when pasting from the context menu.
Maybe I did anticipate pasting but did not test pasting from the menu (I always use Ctrl+C, Ctrl+V).

**Comment by stephanmahieu** [comment]
Fixed with release 2.5.3.1
