### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by wvxwxvw** [stephanmahieu/formhistorycontrol-2#96]
Can I make the date format custom? I don't need years and months in it, a waste of space on the list.

**Comment by stephanmahieu** [comment]
Right now you can't, the old pre-WebExt version did have that option. One of the criticisms for that version was the overwhelming amount of preferences. That is why I dit not implement it in the (completely rewritten) WebExt version.

**Comment by stephanmahieu** [comment]
I can add a few extra option to the selection list without years/months.

**Comment by wvxwxvw** [comment]
Yes, please.

**Comment by stephanmahieu** [comment]
Now available in v2.5.1.0
