### ISSUE TITLE
HTML preview is no longer selectable

### ISSUE THREAD

**Issue by robertmaxton42** [stephanmahieu/formhistorycontrol-2#98]
It is no longer possible to select text in the Form History Control preview window for a given entry. I'm not sure if this is technically a 'bug' or a recent feature, but either way, it's essentially broken FHC for my primary use case, namely keeping drafts of long webforum posts. Many modern text-entry boxes have robust copy-paste support, particularly from existing HTML, but for whatever reason FHC's own copy options don't get recognized, instead just leaving me with a mess of HTML code instead of the formatted text it represents.

Before that didn't matter, because I could just copy the formatted text from within the preview and paste that, but now that that preview isn't selectable anymore I can't actually use a number of my saved drafts.

**Replication**

1. Enter enough formatted text into any page that permits it. *
2. Right click -> Form History Control -> Manage History
3. Select an entry
4. Note that the "Content" field is a mess of HTML. Click on "View: Wiki" at the bottom.
5. The original formatted post appears, but the text is not selectable.

*For a true test, the page should actually permit you to format text in the same box -- not like Github that just automatically inserts Markdown. However, this is not necessary to replicate.

-- As a side note, forcing the text to be selectable with the console doesn't seem to fix the fundamental problem anymore, but that should probably be a separate report.

**Expected behavior**
Either text should be selectable, or the HTML copy-paste function should 'just work' with forum software like XenForo.

**Desktop (please complete the following information):**
 - Windows 10, Firefox 72.0.2, Form History Control 2.5.1.0

**Comment by stephanmahieu** [comment]
There is (and always was) an easier way. Just right-click in the initial window or in one of the preview windows to reveal the copy to clipboard and select either "Copy clean" or "Copy entire content".

Selecting is still possible but its is not highlighted anymore, I will fix that since that is obviously a useful feature.

**Comment by stephanmahieu** [comment]
I will make it so both the new and old ways work. When text is selected, Ctrl-C (or Shift+Ctrl+C) will copy the highlighted text.

**Comment by robertmaxton42** [comment]
Good to hear it. And yeah, I know there's a right-click option, but for whatever reason the forum software I'm using doesn't really handle the resulting copy properly. At some point I should probably figure out exactly what's going wrong there myself...

Thanks!

**Comment by stephanmahieu** [comment]
Fixed with release 2.5.3.1
